#!/bin/bash

sudo apt-get update
sudo apt-get install apache2
# sudo nano /etc/apache2/apache2.conf
# add ServerName _domain or ip_
sudo systemctl restart apache2
sudo ufw app info "Apache Full"
sudo ufw allow in "Apache Full"
sudo apt-get install mysql-server
sudo apt-get install php libapache2-mod-php php-mcrypt php-mysql
sudo systemctl restart apache2
